<?php

namespace CaptainHook\Chargify;

use CaptainHook\Receiver;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;

/**
 *
 * Events emitting webhooks:
 *
 * Event Key                   | Trigger                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | Payload                                                                                                                                                                                                                                                                              |
 * ----------------------------|------------------------------------------------------------------------------------------|
 * signup_success              | Any successful signup (Subscription created) via the API, admin UI, or Public Pages                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | event_id, site, subscription1,9                                                                                                                                                                                                                                         |
 * signup_failure              | Any failed signup (Subscription failed to begin) via the API, admin UI, or Public Pages2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | event_id, site, subscription1                                                                                                                                                                                                                                           |
 * renewal_success             | A successful periodic renewal3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | event_id, site, subscription1                                                                                                                                                                                                                                           |
 * renewal_failure             | A failed periodic renewal, i.e. the credit card is declined3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | event_id, site, subscription1                                                                                                                                                                                                                                           |
 * payment_success             | Any successful payment4 example payload                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | event_id, site, subscription, transaction                                                                                                                                                                                                                                          |
 * payment_failure             | Any failed payment attempt 4 example payload                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | event_id, site, subscription, transaction                                                                                                                                                                                                                                          |
 * billing_date_change         | Any change to the billing date that is initiated explicitly by altering the billing date
 *                               via the admin UI or the API. This will not be triggered upon a normal renewal and period
 *                               advancement, or a migration.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | event_id, site, subscription1 (with previous_billing_date)                                                                                                                                                                                                              |
 * subscription_state_change   | Any change to the Subscription state. This is the “workhorse” of the events – watching
 *                               this event can tell you if a Subscription ever moves to a “bad” state, i.e. past_due                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | event_id, site, subscription1,5                                                                                                                                                                                                                                         |
 * subscription_product_change | A successful change from an old product to a new product for a Subscription.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | event_id, site, previous_product, subscription1                                                                                                                                                                                                                         |
 * subscription_card_update    | Any change to the active Credit Card type payment profile.7,8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | event_id, site, subscription,product, previous_payment_profile, updated_payment_profile                                                                                                                                                                                            |
 * expiring_card               | A periodic event sent by Chargify                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | event_id, site, subscription 1, 6                                                                                                                                                                                                                                       |
 * customer_update             | Any change to the following customer fields: first_name, last_name, organization, email,
 *                               reference, address, address 2, city, state, zip, country, phone.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | event_id, site, customer                                                                                                                                                                                                                                                           |
 * component_allocation_change | Any change to a subscription’s quantity-based component allocation or enabled status of
 *                               an on/off component that is made after signup. This webhook does not fire if allocations
 *                               are set as a part of the subscription creation (i.e. signup) – it only fires upon
 *                               subsequent changes. previous_allocation and new_allocation give the allocation values
 *                               before and after the change. These will be either 0 or 1 for On/Off Components to
 *                               represent off and on, respectively. timestamp provides the date and time the allocation
 *                               was recorded and is listed in ISO8601 format in the UTC timezone. Note: this timestamp
 *                               format differs slightly from the format of existing timestamps in other event types and
 *                               represents our new direction for webhook timestamps.                                     | event_id, site[id], site[subdomain], component[id], component[name], component[unit_name], component[kind], subscription[id], subscription[name], product[id], product[name], previous_allocation, new_allocation, memo, timestamp                    |
 * metered_usage               | Any reported usage for a subscription’s metered components. This webhook will not fire
 *                               when the unit balance is reset to 0 at the time of renewal.timestamp provides the date
 *                               and time the usage was recorded and is listed in ISO8601 format in the UTC timezone.
 *                               Note: this timestamp format differs slightly from the format of existing timestamps in
 *                               other event types and represents our new direction for webhook timestamps.                                                                                                                                                                                                                                                                                                                               | event_id, site[id], site[subdomain], component[id], component[name], component[unit_name], component[kind], subscription[id], subscription[name], product[id], product[name], previous_unit_balance, new_unit_balance, usage_quantity, memo, timestamp |
 * upgrade_downgrade_success   | Any successful upgrade/downgrade                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | event_id, site, subscription1, previous_product                                                                                                                                                                                                                          |
 * upgrade_downgrade_failure   | Any failed upgrade/downgrade                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | event_id, site, subscription1, previous_product                                                                                                                                                                                                                          |
 * refund_success              | Any successful refund                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | Example Payload                                                                                                                                                                                                                                                |
 * refund_failure              | Any failed refund                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | Example Payload                                                                                                                                                                                                                                                |
 * upcoming_renewal_notice     | A subscription set to renew within 3 days. Example payload                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | customer, email_sent, estimated_renewal_amount_in_cents, event_id, message, payment_profile, product, site, subscription                                                                                                                                            |
 * trial_end_notice            | A trial set to end within 3 days. Example payload                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | customer, email_sent, estimated_renewal_amount_in_cents, event_id, message, payment_profile, product, site, subscription                                                                                                                                         |
 * statement_closed            | A statement closes Statement Events                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | Example Payload                                                                                                                                                                                                                                                |
 * statement_settled           | A statement settles Statement Events                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | Example Payload                                                                                                                                                                                                                                                |
 * expiration_date_change      | A subscriptions expires_at timestamp is updated                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Example Payload                                                                                                                                                                                                                                                |
 * dunning_step_reached        | A dunning step has been reached                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Example Payload
 */
final class Chargify implements Receiver
{
    const SIGNUP_SUCCESS = 'signup_success';
    const SIGNUP_FAILURE = 'signup_failure';

    /**
     *
     * @param RequestInterface $request
     *
     * @return bool
     */
    public function canHandle(RequestInterface $request): bool
    {
        return $request->hasHeader('X-Chargify-Webhook-Signature-Hmac-Sha-256');
    }

    /**
     *
     * @param RequestInterface $request
     * @param ResponseInterface $response
     */
    public function __invoke(RequestInterface $request, Response $response)
    {

    }

    private function validateSignature($signature, $shared_key, $raw_post)
    {
        if(hash_hmac('sha256', $raw_post, $shared_key) == $signature) { return true; }

        return false;
    }
}
